from enum import Enum

class ErrorCode(str, Enum):
    DEFAULT = "DEFAULT"
    EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS"
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    SERVER_ERROR = "SERVER_ERROR"